include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    avoid_web_libraries_in_flutter: true
    avoid_void_async: true
    avoid_print: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    slash_for_doc_comments: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    void_checks: true
